version: '3'
services:
  wordpress:
    image: "wordpress:${WORDPRESS_VERSION:-latest}"
    restart: always
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-wordpress}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-A7yXSYuJBSIixu}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}"
    volumes:
      - ./app/wp-content:/var/www/html/wp-content/
      - ./config/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME:-wordpress}"
      MYSQL_USER: "${WORDPRESS_DB_USER:-wordpress}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD:-A7yXSYuJBSIixu}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql